---
  - debug:
      msg: "Variable is {{ ansible_os_family }}"
  - name: install list of packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
    - git
    - epel-release
    - python3
    when: ansible_os_family == "RedHat"
  - name: Upgrade pip
    pip:
      name: pip
      executable: pip3
      state: latest
    when: ansible_os_family == "RedHat" 
  - name: git clone repo
    git:
      repo: "{{git_url}}"
      dest: "{{dest_folder}}"
    when: ansible_os_family == "RedHat"
  - name: install requirements
    pip:
      requirements: /opt/flaskex/requirements.txt
      executable: pip3
    when: ansible_os_family == "RedHat"
  - name: Run Python script in background
    command: "nohup python3 /opt/flaskex/app.py > /dev/null 2>&1 &"
    when: ansible_os_family == "RedHat"