- hosts: all
  become: yes
  tasks:

  - name: Install All required packagess for python2 app
    import_role:
      name: requirements
  - name: Git clone the application
    import_role:
      name: git_clone

  - name: install requirements for application
    pip:
      requirements: /opt/flaskex/requirements.txt
  - name: Start App

    shell: "pkill app.py; nohup python app.py &"
    args:
      chdir: /opt/flaskex