- hosts: all
  become: yes
  tasks:

  - name: install all packages for java app
    import_role: 
      name: java17_packages

  - name: Git clone the application
    import_role:
      name: git_clone

  - name: Run Maven Wrappen
    command: './mvnw package'
    args:
      chdir: /opt/petclinic
      creates: /opt/petclinic/target

  - name: Start App
    shell: 'pkill java; sleep 3; nohup java -jar /opt/petclinic/target/spring-petclinic-3.0.0-SNAPSHOT.jar &'
    args:
      chdir: /opt/petclinic

