---
 - name: install list of packages
   yum:
     name: "{{ item }}"
     state: present
   with_items:
    - git

 - name: Check if pip is installed
   command: pip --version
   register: pip_check
   changed_when: false
 - name: Install pip for Python 2
   shell: "curl -s https://bootstrap.pypa.io/get-pip.py | python"
   when: pip_check.rc != 0
