- hosts: all
  tasks:
  - debug:
      msg: "Variable is {{ ansible_os_family }}"

  - name: Disable SELinux
    selinux:
      state: disabled
    when: ansible_os_family == "RedHat"

  - name: Install Apache on CentOS
    yum:
      name: httpd
      state: latest
    when: ansible_os_family == "RedHat"

  - name: Install apache httpd on Ubuntu  (state=present is optional)
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: Make sure a service is running
    systemd:
      state: started
      enabled: yes
      name: httpd
    when: ansible_os_family == "RedHat"

  - name: Start Apache
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_os_family == "Debian"

  - name: Download template
    get_url:
      url: https://www.free-css.com/assets/files/free-css-templates/download/page291/goid.zip
      dest: /tmp/

  - name: Install Unzip on CentOS
    yum:
      name: unzip
      state: latest
    when: ansible_os_family == "RedHat"

  - name: Install Unzip on Ubuntu
    apt:
      name: unzip
      state: latest
    when: ansible_os_family == "Debian"

  - name: Extract a template
    unarchive:
      src: /tmp/goid.zip
      dest: /var/www
      remote_src: yes
      
  - name: Move templates files to /var/www/html
    shell: "mv /var/www/goid-html/* /var/www/html/"
    args:
      creates: /var/www//index.html 